#include <bits/stdc++.h>

using namespace std;

string convert(string s) {
    if(s.compare("Afghanistan")==0) return "AF";
    if(s.compare("Åland Islands")==0) return "AX";
    if(s.compare("Albania")==0) return "AL";
    if(s.compare("Algeria")==0) return "DZ";
    if(s.compare("American Samoa")==0) return "AS";
    if(s.compare("Andorra")==0) return "AD";
    if(s.compare("Angola")==0) return "AO";
    if(s.compare("Anguilla")==0) return "AI";
    if(s.compare("Antarctica")==0) return "AQ";
    if(s.compare("Antigua and Barbuda")==0) return "AG";
    if(s.compare("Argentina")==0) return "AR";
    if(s.compare("Armenia")==0) return "AM";
    if(s.compare("Aruba")==0) return "AW";
    if(s.compare("Australia")==0) return "AU";
    if(s.compare("Austria")==0) return "AT";
    if(s.compare("Azerbaijan")==0) return "AZ";
    if(s.compare("Bahamas")==0) return "BS";
    if(s.compare("Bahrain")==0) return "BH";
    if(s.compare("Bangladesh")==0) return "BD";
    if(s.compare("Barbados")==0) return "BB";
    if(s.compare("Belarus")==0) return "BY";
    if(s.compare("Belgium")==0) return "BE";
    if(s.compare("Belize")==0) return "BZ";
    if(s.compare("Benin")==0) return "BJ";
    if(s.compare("Bermuda")==0) return "BM";
    if(s.compare("Bhutan")==0) return "BT";
    if(s.compare("Bolivia")==0) return "BO";
    if(s.compare("Bonaire, Sint Eustatius and Saba")==0) return "BQ";
    if(s.compare("Bosnia and Herzegovina")==0) return "BA";
    if(s.compare("Botswana")==0) return "BW";
    if(s.compare("Brazil")==0) return "BR";
    if(s.compare("British Indian Ocean Territory")==0) return "IO";
    if(s.compare("Brunei Darussalam")==0) return "BN";
    if(s.compare("Bulgaria")==0) return "BG";
    if(s.compare("Burkina Faso")==0) return "BF";
    if(s.compare("Burundi")==0) return "BI";
    if(s.compare("Cambodia")==0) return "KH";
    if(s.compare("Cameroon")==0) return "CM";
    if(s.compare("Canada")==0) return "CA";
    if(s.compare("Cape Verde")==0) return "CV";
    if(s.compare("Cayman Islands")==0) return "KY";
    if(s.compare("Central African Republic")==0) return "CF";
    if(s.compare("Chad")==0) return "TD";
    if(s.compare("Chile")==0) return "CL";
    if(s.compare("China")==0) return "CN";
    if(s.compare("Christmas Island")==0) return "CX";
    if(s.compare("Cocos (Keeling) Islands")==0) return "CC";
    if(s.compare("Colombia")==0) return "CO";
    if(s.compare("Comoros")==0) return "KM";
    if(s.compare("Congo")==0) return "CG";
    if(s.compare("Congo, The Democratic Republic of the")==0) return "CD";
    if(s.compare("Cook Islands")==0) return "CK";
    if(s.compare("Costa Rica")==0) return "CR";
    if(s.compare("Côte d'Ivoire")==0) return "CI";
    if(s.compare("Croatia")==0) return "HR";
    if(s.compare("Cuba")==0) return "CU";
    if(s.compare("Curaçao")==0) return "CW";
    if(s.compare("Cyprus")==0) return "CY";
    if(s.compare("Czech Republic")==0) return "CZ";
    if(s.compare("Denmark")==0) return "DK";
    if(s.compare("Djibouti")==0) return "DJ";
    if(s.compare("Dominica")==0) return "DM";
    if(s.compare("Dominican Republic")==0) return "DO";
    if(s.compare("Ecuador")==0) return "EC";
    if(s.compare("Egypt")==0) return "EG";
    if(s.compare("El Salvador")==0) return "SV";
    if(s.compare("Equatorial Guinea")==0) return "GQ";
    if(s.compare("Eritrea")==0) return "ER";
    if(s.compare("Estonia")==0) return "EE";
    if(s.compare("Ethiopia")==0) return "ET";
    if(s.compare("Falkland Islands (Malvinas)")==0) return "FK";
    if(s.compare("Faroe Islands")==0) return "FO";
    if(s.compare("Fiji")==0) return "FJ";
    if(s.compare("Finland")==0) return "FI";
    if(s.compare("France")==0) return "FR";
    if(s.compare("French Guiana")==0) return "GF";
    if(s.compare("French Polynesia")==0) return "PF";
    if(s.compare("French Southern Territories")==0) return "TF";
    if(s.compare("Gabon")==0) return "GA";
    if(s.compare("Gambia")==0) return "GM";
    if(s.compare("Georgia")==0) return "GE";
    if(s.compare("Germany")==0) return "DE";
    if(s.compare("Ghana")==0) return "GH";
    if(s.compare("Gibraltar")==0) return "GI";
    if(s.compare("Greece")==0) return "GR";
    if(s.compare("Greenland")==0) return "GL";
    if(s.compare("Grenada")==0) return "GD";
    if(s.compare("Guadeloupe")==0) return "GP";
    if(s.compare("Guam")==0) return "GU";
    if(s.compare("Guatemala")==0) return "GT";
    if(s.compare("Guernsey")==0) return "GG";
    if(s.compare("Guinea")==0) return "GN";
    if(s.compare("Guinea-Bissau")==0) return "GW";
    if(s.compare("Guyana")==0) return "GY";
    if(s.compare("Haiti")==0) return "HT";
    if(s.compare("Heard Island and McDonald Islands")==0) return "HM";
    if(s.compare("Holy See (Vatican City State)")==0) return "VA";
    if(s.compare("Honduras")==0) return "HN";
    if(s.compare("Hong Kong")==0) return "HK";
    if(s.compare("Hungary")==0) return "HU";
    if(s.compare("Iceland")==0) return "IS";
    if(s.compare("India")==0) return "IN";
    if(s.compare("Indonesia")==0) return "ID";
    if(s.compare("Installations in International Waters")==0) return "XZ";
    if(s.compare("Iran, Islamic Republic of")==0) return "IR";
    if(s.compare("Iraq")==0) return "IQ";
    if(s.compare("Ireland")==0) return "IE";
    if(s.compare("Isle of Man")==0) return "IM";
    if(s.compare("Israel")==0) return "IL";
    if(s.compare("Italy")==0) return "IT";
    if(s.compare("Jamaica")==0) return "JM";
    if(s.compare("Japan")==0) return "JP";
    if(s.compare("Jersey")==0) return "JE";
    if(s.compare("Jordan")==0) return "JO";
    if(s.compare("Kazakhstan")==0) return "KZ";
    if(s.compare("Kenya")==0) return "KE";
    if(s.compare("Kiribati")==0) return "KI";
    if(s.compare("Korea, Democratic People's Republic of")==0) return "KP";
    if(s.compare("Korea, Republic of")==0) return "KR";
    if(s.compare("Kuwait")==0) return "KW";
    if(s.compare("Kyrgyzstan")==0) return "KG";
    if(s.compare("Lao People's Democratic Republic")==0) return "LA";
    if(s.compare("Latvia")==0) return "LV";
    if(s.compare("Lebanon")==0) return "LB";
    if(s.compare("Lesotho")==0) return "LS";
    if(s.compare("Liberia")==0) return "LR";
    if(s.compare("Libya")==0) return "LY";
    if(s.compare("Liechtenstein")==0) return "LI";
    if(s.compare("Lithuania")==0) return "LT";
    if(s.compare("Luxembourg")==0) return "LU";
    if(s.compare("Macao")==0) return "MO";
    if(s.compare("Macedonia, The former Yugoslav Republic of")==0) return "MK";
    if(s.compare("Madagascar")==0) return "MG";
    if(s.compare("Malawi")==0) return "MW";
    if(s.compare("Malaysia")==0) return "MY";
    if(s.compare("Maldives")==0) return "MV";
    if(s.compare("Mali")==0) return "ML";
    if(s.compare("Malta")==0) return "MT";
    if(s.compare("Marshall Islands")==0) return "MH";
    if(s.compare("Martinique")==0) return "MQ";
    if(s.compare("Mauritania")==0) return "MR";
    if(s.compare("Mauritius")==0) return "MU";
    if(s.compare("Mayotte")==0) return "YT";
    if(s.compare("Mexico")==0) return "MX";
    if(s.compare("Micronesia, Federated States of")==0) return "FM";
    if(s.compare("Moldova, Republic of")==0) return "MD";
    if(s.compare("Monaco")==0) return "MC";
    if(s.compare("Mongolia")==0) return "MN";
    if(s.compare("Montenegro")==0) return "ME";
    if(s.compare("Montserrat")==0) return "MS";
    if(s.compare("Morocco")==0) return "MA";
    if(s.compare("Mozambique")==0) return "MZ";
    if(s.compare("Myanmar")==0) return "MM";
    if(s.compare("Namibia")==0) return "NA";
    if(s.compare("Nauru")==0) return "NR";
    if(s.compare("Nepal")==0) return "NP";
    if(s.compare("Netherlands")==0) return "NL";
    if(s.compare("New Caledonia")==0) return "NC";
    if(s.compare("New Zealand")==0) return "NZ";
    if(s.compare("Nicaragua")==0) return "NI";
    if(s.compare("Niger")==0) return "NE";
    if(s.compare("Nigeria")==0) return "NG";
    if(s.compare("Niue")==0) return "NU";
    if(s.compare("Norfolk Island")==0) return "NF";
    if(s.compare("Northern Mariana Islands")==0) return "MP";
    if(s.compare("Norway")==0) return "NO";
    if(s.compare("Oman")==0) return "OM";
    if(s.compare("Pakistan")==0) return "PK";
    if(s.compare("Palau")==0) return "PW";
    if(s.compare("Palestine, State of")==0) return "PS";
    if(s.compare("Panama")==0) return "PA";
    if(s.compare("Papua New Guinea")==0) return "PG";
    if(s.compare("Paraguay")==0) return "PY";
    if(s.compare("Peru")==0) return "PE";
    if(s.compare("Philippines")==0) return "PH";
    if(s.compare("Pitcairn")==0) return "PN";
    if(s.compare("Poland")==0) return "PL";
    if(s.compare("Portugal")==0) return "PT";
    if(s.compare("Puerto Rico")==0) return "PR";
    if(s.compare("Qatar")==0) return "QA";
    if(s.compare("Reunion")==0) return "RE";
    if(s.compare("Romania")==0) return "RO";
    if(s.compare("Russian Federation")==0) return "RU";
    if(s.compare("Rwanda")==0) return "RW";
    if(s.compare("Saint Barthélemy")==0) return "BL";
    if(s.compare("Saint Helena, Ascension and Tristan Da Cunha")==0) return "SH";
    if(s.compare("Saint Kitts and Nevis")==0) return "KN";
    if(s.compare("Saint Lucia")==0) return "LC";
    if(s.compare("Saint Martin (French Part)")==0) return "MF";
    if(s.compare("Saint Pierre and Miquelon")==0) return "PM";
    if(s.compare("Saint Vincent and the Grenadines")==0) return "VC";
    if(s.compare("Samoa")==0) return "WS";
    if(s.compare("San Marino")==0) return "SM";
    if(s.compare("Sao Tome and Principe")==0) return "ST";
    if(s.compare("Saudi Arabia")==0) return "SA";
    if(s.compare("Senegal")==0) return "SN";
    if(s.compare("Serbia")==0) return "RS";
    if(s.compare("Seychelles")==0) return "SC";
    if(s.compare("Sierra Leone")==0) return "SL";
    if(s.compare("Singapore")==0) return "SG";
    if(s.compare("Sint Maarten (Dutch Part)")==0) return "SX";
    if(s.compare("Slovakia")==0) return "SK";
    if(s.compare("Slovenia")==0) return "SI";
    if(s.compare("Solomon Islands")==0) return "SB";
    if(s.compare("Somalia")==0) return "SO";
    if(s.compare("South Africa")==0) return "ZA";
    if(s.compare("South Georgia and the South Sandwich Islands")==0) return "GS";
    if(s.compare("South Sudan")==0) return "SS";
    if(s.compare("Spain")==0) return "ES";
    if(s.compare("Sri Lanka")==0) return "LK";
    if(s.compare("Sudan")==0) return "SD";
    if(s.compare("Suriname")==0) return "SR";
    if(s.compare("Svalbard and Jan Mayen")==0) return "SJ";
    if(s.compare("Swaziland")==0) return "SZ";
    if(s.compare("Sweden")==0) return "SE";
    if(s.compare("Switzerland")==0) return "CH";
    if(s.compare("Syrian Arab Republic")==0) return "SY";
    if(s.compare("Taiwan, Province of China")==0) return "TW";
    if(s.compare("Tajikistan")==0) return "TJ";
    if(s.compare("Tanzania, United Republic of")==0) return "TZ";
    if(s.compare("Thailand")==0) return "TH";
    if(s.compare("Timor-Leste")==0) return "TL";
    if(s.compare("Togo")==0) return "TG";
    if(s.compare("Tokelau")==0) return "TK";
    if(s.compare("Tonga")==0) return "TO";
    if(s.compare("Trinidad and Tobago")==0) return "TT";
    if(s.compare("Tunisia")==0) return "TN";
    if(s.compare("Turkey")==0) return "TR";
    if(s.compare("Turkmenistan")==0) return "TM";
    if(s.compare("Turks and Caicos Islands")==0) return "TC";
    if(s.compare("Tuvalu")==0) return "TV";
    if(s.compare("Uganda")==0) return "UG";
    if(s.compare("Ukraine")==0) return "UA";
    if(s.compare("United Arab Emirates")==0) return "AE";
    if(s.compare("United Kingdom")==0) return "GB";
    if(s.compare("United States")==0) return "US";
    if(s.compare("United States Minor Outlying Islands")==0) return "UM";
    if(s.compare("Uruguay")==0) return "UY";
    if(s.compare("Uzbekistan")==0) return "UZ";
    if(s.compare("Vanuatu")==0) return "VU";
    if(s.compare("Venezuela")==0) return "VE";
    if(s.compare("Viet Nam")==0) return "VN";
    if(s.compare("Virgin Islands, British")==0) return "VG";
    if(s.compare("Virgin Islands, U.S.")==0) return "VI";
    if(s.compare("Wallis and Futuna")==0) return "WF";
    if(s.compare("Western Sahara")==0) return "EH";
    if(s.compare("Yemen")==0) return "YE";
    if(s.compare("Zambia")==0) return "ZM";
    if(s.compare("Zimbabwe")==0) return "ZW";
    return "ZZ";
}

int main() {
    string s;
    while(getline(cin, s)) {
        cout << convert(s) << " " << s << endl;
    }
}
